model_name = "willcb/Qwen3-4B"
dataset = "PrimeIntellect/reverse_text_dataset_debug_50_seq_len"
batch_size = 16
dp = 1
rollout_path = "outputs"
output_path = "data_rollout"
max_model_len = 128
clean_output_path = true
total_step = 50